# config/config.yml
embedding_dim: 384
faiss_index: /home/tanay/Projects/smart-mail/data/embeddings.faiss
meta_db: /home/tanay/Projects/smart-mail/data/meta.sqlite
llama_bin: /home/tanay/llama.cpp/build/bin/llama-cli
llama_model: /home/tanay/Projects/smart-mail/models/instruction/mistral-7b-instruct-v0.2.Q3_K_L.gguf
embed_bin: /home/tanay/llama.cpp/build/bin/llama-embedding
embed_model: /home/tanay/Projects/smart-mail/models/embedding/bge-small-en-v1.5-f32.gguf
